# 测试服务
hello_world_runner:
  logger:
    log_file: "logs/hello_world_runner.log"
    log_console: true
    level: "DEBUG"
    local_time: true
  listen_addr: "127.0.0.1:28081"

# 微信机器人服务
wxauto_runner:
  logger:
    log_file: "logs/wxauto_runner.log"
    log_console: true
    level: "DEBUG"
    local_time: true

  producer:
    nats_url: "nats://192.168.242.2:4222"
    subject: "BOTS.send_msgs"

  consumer:
    nats_url: "nats://192.168.242.2:4222"
    concurrency: 2
    subject: "BOTS.received_msgs"
    consumer_name: "WX_MSGS_CONSUMER"

  react_agent:
    system_prompt: "你是一个人工智能助手，你有一些工具可以调用，请根据用户需求调用相关工具，最终言简意赅回答用户结果"
    model:
      base_url: "https://api.deepseek.com"
      api_key: "<API_KEY>"
      model: "deepseek-chat"

  user_message_template: |
    你收到了消息：
      消息ID：{{.ID}}
      消息类型：{{.Type}}
      消息属性：{{.Attr}}
      消息内容：{{.Content}}
      发送人：{{.Sender}}
      发送人备注：{{.SenderRemark}}
      会话类型：{{.Info.ChatType}}
      会话名称：{{.Info.ChatName}}
      {{- if .Info.GroupMemberCount}}
      群成员数量：{{.Info.GroupMemberCount}}
      {{- end}}
    请你作为一个微信机器人，以第一人称来处理以上消息，并给出简洁的回复。

  # 基于 Expr 语言的用户消息过滤器
  user_message_reply_filter: |
    string(Type) == "text" && 
    Content != "" && 
    len(Content) < 100 &&
    Content contains "bot"
