logger:
  log_file: "./app.log"
  level: "DEBUG"
  local_time: true

consumer:
  nats_url: "nats://192.168.242.2:4222"
  concurrency: 2
  subject: "BOTS.received_msgs"
  consumer_name: "WX_MSGS_CONSUMER"
