logger:
  level: DEBUG
  filename: app.log

nats_url: nats://192.168.242.2:4222

chat_transfer_config:
  - chat: "机器人儿"
    subject: "BOTS.received_msgs"
  - chat: "zzq"
    subject: "BOTS.received_msgs"
