logger:
  level: DEBUG
  filename: app.log

nats_url: nats://192.168.242.2:4222

chat_transfer_config:
  - chat: "梦中coding项目事故调查"
    subject: "BOTS.received_msgs"
  - chat: "zzq"
    subject: "BOTS.received_msgs"
  - chat: "吃饭"
    subject: "BOTS.received_msgs"
  - chat: "enfp们的sit秘密基地"
    subject: "BOTS.received_msgs"