logger:
  level: DEBUG
  filename: app.log

nats_url: nats://192.168.242.2:4222

chat_transfer_config:
  - chat: "梦中coding项目事故调查"
    subject: "BOTS.received_msgs"
  - chat: "zzq"
    subject: "BOTS.received_msgs"
  - chat: "吃饭"
    subject: "BOTS.received_msgs"
  - chat: "enfp们的sit秘密基地"
    subject: "BOTS.received_msgs"
  - chat: "SIT-YoHe 好的，总裁"
    subject: "BOTS.received_msgs"
  - chat: "当0当1不如当3 & 回避研究所"
    subject: "BOTS.received_msgs"
  - chat: "【上应Game】崩铁&原神&zzz"
    subject: "BOTS.received_msgs"
  - chat: "SIT江西老乡群"
    subject: "BOTS.received_msgs"